# Generated by Django 4.2.3 on 2023-07-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0004_teacher_additional_details_teacher_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='additional_details',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='country',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='education',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='state',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
        migrations.AddField(
            model_name='diaryuser',
            name='additional_details',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='diaryuser',
            name='country',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='diaryuser',
            name='education',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='diaryuser',
            name='experience',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='diaryuser',
            name='phone',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='diaryuser',
            name='state',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='diaryuser',
            name='subjects',
            field=models.ManyToManyField(to='account_app.subject'),
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ManyToManyField(to='account_app.teacher'),
        ),
        migrations.AlterField(
            model_name='diaryuser',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
