# Generated by Django 4.2.3 on 2023-07-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0005_remove_teacher_additional_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryuser',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='diaryuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='diaryuser',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
