# Generated by Django 4.2.3 on 2023-07-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0007_student_teacher_subject_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lesson_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
