# Generated by Django 4.2.3 on 2023-07-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0010_student_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='files',
            field=models.URLField(blank=True, null=True),
        ),
    ]
