# Generated by Django 4.2.3 on 2023-07-30 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0011_alter_student_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='files',
        ),
    ]
