# Generated by Django 4.2.3 on 2023-08-05 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0014_remove_student_files'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='TeachersSubject',
        ),
        migrations.RemoveField(
            model_name='diaryuser',
            name='subjects',
        ),
    ]
