# Generated by Django 4.2.3 on 2023-08-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0016_alter_group_students_remove_group_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='lesson_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
