# Generated by Django 4.2.3 on 2023-08-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0020_alter_group_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='more_information',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
