# Generated by Django 4.2.3 on 2023-08-08 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0021_student_more_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='account_app.teacherssubject'),
            preserve_default=False,
        ),
    ]
