# Generated by Django 4.2.3 on 2023-08-09 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0024_alter_group_subject_alter_student_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
