# Generated by Django 4.2.3 on 2023-08-09 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0025_remove_student_subject_remove_student_teacher_and_more'),
        ('event_app', '0005_alter_event_lesson_with'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
