# Generated by Django 4.2.3 on 2023-08-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0026_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherssubject',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
