# Generated by Django 4.2.3 on 2023-08-09 17:43

from django.db import migrations, models
import my_diary.account_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0027_alter_teacherssubject_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[my_diary.account_app.models.validate_phone_number]),
        ),
    ]
