# Generated by Django 4.2.3 on 2023-07-26 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0002_rename_title_event_name_remove_event_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
