# Generated by Django 4.2.3 on 2023-08-02 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account_app', '0014_remove_student_files'),
        ('event_app', '0003_remove_teacher_subjects_delete_group_delete_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lesson_with',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='account_app.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='teacher',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
