# Generated by Django 4.2.3 on 2023-08-09 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students_and_groups', '0001_initial'),
        ('event_app', '0004_event_lesson_with_event_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='lesson_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_and_groups.student'),
        ),
    ]
