# Generated by Django 4.2.3 on 2023-08-09 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students_and_groups', '0001_initial'),
        ('event_app', '0005_alter_event_lesson_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lesson_with_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students_and_groups.group'),
        ),
        migrations.AlterField(
            model_name='event',
            name='lesson_with',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students_and_groups.student'),
        ),
    ]
