# Generated by Django 4.2.3 on 2023-08-09 16:56

from django.db import migrations, models
import my_diary.students_and_groups.models


class Migration(migrations.Migration):

    dependencies = [
        ('students_and_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[my_diary.students_and_groups.models.validate_phone_number]),
        ),
    ]
